import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.util.Calendar;
import java.util.GregorianCalendar;

public class DateTimePicker implements ChangeListener
{
    private JSpinner daySpinner;
    private JSpinner monthSpinner;
    private JSpinner yearSpinner;
    private JPanel rootPanel = new JPanel();
    private JSpinner hourSpinner;
    private JSpinner minSpinner;
    private JSpinner secSpinner;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    void addSpinner (JSpinner sp)
    {
        sp.addChangeListener(this);
        rootPanel.add(sp);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$ ()
    {
        rootPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));

        rootPanel.add(new JLabel("Day"));

        SpinnerModel spm = new SpinnerNumberModel(1,1,31,1);
        daySpinner = new JSpinner(spm);
        daySpinner.setPreferredSize(new Dimension(40, 20));
        addSpinner(daySpinner);

        rootPanel.add(new JLabel("Month"));

        spm = new SpinnerNumberModel(1,1,12,1);
        monthSpinner = new JSpinner(spm);
        monthSpinner.setPreferredSize(new Dimension(40, 20));
        addSpinner(monthSpinner);

        rootPanel.add(new JLabel("Year"));

        spm = new SpinnerNumberModel(2018,2018,2050,1);
        yearSpinner = new JSpinner(spm);
        yearSpinner.setPreferredSize(new Dimension(50, 20));
        addSpinner(yearSpinner);

        rootPanel.add(new JLabel("Hour"));

        spm = new SpinnerNumberModel(0,0,23,1);
        hourSpinner = new JSpinner(spm);
        hourSpinner.setPreferredSize(new Dimension(50, 20));
        addSpinner(hourSpinner);

        rootPanel.add(new JLabel("Min"));

        spm = new SpinnerNumberModel(0,0,59,1);
        minSpinner = new JSpinner(spm);
        minSpinner.setPreferredSize(new Dimension(50, 20));
        addSpinner(minSpinner);

        rootPanel.add(new JLabel("Sec"));

        spm = new SpinnerNumberModel(0,0,59,1);
        secSpinner = new JSpinner(spm);
        secSpinner.setPreferredSize(new Dimension(50, 20));
        addSpinner(secSpinner);
    }

    public static void main (String[] args)
    {
        JFrame frame = new JFrame("DateTimePicker");
        frame.setContentPane(new DateTimePicker().rootPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }


    @Override
    public void stateChanged (ChangeEvent e)
    {
        Integer y = (Integer) yearSpinner.getValue();
        Integer m = (Integer) monthSpinner.getValue();
        Integer d = (Integer) daySpinner.getValue();
        Integer hou = (Integer) hourSpinner.getValue();
        Integer min = (Integer) minSpinner.getValue();
        Integer sec = (Integer) secSpinner.getValue();

        Calendar cal = new GregorianCalendar(y, m-1, d, hou, min, sec);
        System.out.println(cal.getTime());
    }
}
